apiVersion: batch/v1
kind: Job
metadata:
  name: file-cleanup-job
spec:
  template:
    spec:
      containers:
      - name: file-cleanup
        image: file-cleanup:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DAYS_OLD
          value: "7"
        volumeMounts:
        - name: data
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: data
        hostPath:
          path: /Users/rahulbansod01/Projects/devops-labs/file-cleanup/data
